DEFAULT_ORDER_METHOD = "greedy"

DEFAULT_SLICE_METHOD = "parallelism"
DEFAULT_SLICE_COUNT = 5
# DEFAULT_SLICE_METHOD = "memory"
DEFAULT_SLICE_WIDTH = 20

DEFAULT_ORDER_UPDATE = False

DEFAULT_EXECUTION_METHOD = "serial"
# DEFAULT_EXECUTION_METHOD = "cpu_parallel"
# DEFAULT_EXECUTION_METHOD = "gpu_parallel"

