cc_library(
    name = "tsl_robin_map",
    hdrs = glob([
        "bit_set/robin-map/include/tsl/*.h",
    ], allow_empty = True),
    includes = ["bit_set/robin-map/include"],
    visibility = ["//visibility:public"],
)


cc_library(
    name = "robin_hood",
    hdrs = glob([
        "bit_set/robin-hood-hashing/src/include/*.h",
    ], allow_empty = True),
    includes = ["bit_set/robin-hood-hashing/src/include"],
    visibility = ["//visibility:public"],
)
